# Generated by Django 5.0.2 on 2024-02-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ops', 'Operations User'), ('client', 'Client User')], default='client', max_length=20),
        ),
    ]
